package com.forero.infrastructure.mapper;

import com.forero.domain.model.User;
import com.forero.infrastructure.adapter.entity.UserEntity;
import com.forero.infrastructure.dto.request.UserRequestDto;
import com.forero.infrastructure.dto.response.UserResponseDto;
import org.springframework.stereotype.Component;

@Component
public class UserMapperImplementation implements UserMapper {
    @Override
    public User toModel(final UserRequestDto userRequestDto) {
        if (userRequestDto == null) {
            return null;
        }
        return new User(
                null, // ID will be generated by MongoDB
                userRequestDto.name(),
                userRequestDto.email(),
                userRequestDto.phone(),
                userRequestDto.address()
        );
    }

    @Override
    public UserResponseDto toDto(final User user) {
        if (user == null) {
            return null;
        }
        return new UserResponseDto(user.id(), user.name());
    }

    @Override
    public User toModel(final UserEntity userEntity) {
        if (userEntity == null) {
            return null;
        }
        return new User(
                userEntity.getId(),
                userEntity.getName(),
                userEntity.getEmail(),
                userEntity.getPhone(),
                userEntity.getAddress()
        );
    }

    @Override
    public UserEntity toEntity(final User user) {
        if (user == null) {
            return null;
        }
        final UserEntity userEntity = new UserEntity();
        userEntity.setId(user.id());
        userEntity.setName(user.name());
        userEntity.setEmail(user.email());
        userEntity.setPhone(user.phone());
        userEntity.setAddress(user.address());
        return userEntity;
    }
}
